name: insulin_calculator
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  flutter_launcher_icons: ^0.12.0
  photo_view: ^0.14.0
  shared_preferences: ^2.1.0
  flutter_phone_direct_caller: ^2.1.1
  hexcolor: ^3.0.1
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.4
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:

  image_path: "assets/images/LOGO.jpg"
  adaptive_icon_background: "#ffffff" #"assets/icon/logo.png"
  adaptive_icon_foreground: "assets/images/LOGO.jpg"
  android: true
  ios: true # can specify file name here e.g. "My-Launcher-Icon"


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/images/breakfast/
     - assets/images/vegtable/
     - assets/images/dinner/
     - assets/images/nuts/
     - assets/images/cinabbon/
     - assets/images/kfc/
     - assets/images/mac/
     - assets/images/street/
     - assets/images/supermarket/
  #   - images/a_dot_ham.jpeg


  # example:
  fonts:
     - family: Tajawal
       fonts:
         - asset: assets/fonts/Tajawal-Medium.ttf
         - asset: assets/fonts/Tajawal-Medium.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
